name: Testing stuff

on:
  push:
    branches:
      - master

jobs:
  a_test_job:
    runs-on: ubuntu-20.04
    steps:
      - uses: actions/checkout@v2
      - name: github context
        env:
          GITHUB_CONTEXT: ${{ toJson(github) }}
        run: echo "$GITHUB_CONTEXT"
      - name: github event name
        env:
          GITHUB_EVENT_NAME: ${{ toJson(github.event_name) }}
        run: echo "$GITHUB_EVENT_NAME"
      - name: commits
        env:
          COMMITS: ${{ toJson(github.event.commits) }}
        run: echo "$COMMITS"
      - name: commit messages
        env:
          COMMIT_MESSAGES: ${{ toJson(github.event.commits.*.message) }}
        run: echo "$COMMIT_MESSAGES"
      - name: commit messages contains skip
        env:
          CONTAINS_SKIP: ${{ contains(toJson(join(github.event.commits.*.message)), '#skip') }}
        run: echo "$CONTAINS_SKIP"
      - name: run tagging and deployment on master branch
        env:
          RUN_TAGGING_AND_DEPLOYMENT_ON_MASTER: ${{ github.event_name == 'push' && !contains(toJson(join(github.event.commits.*.message)), '#skip') }}
        run: echo "$RUN_TAGGING_AND_DEPLOYMENT_ON_MASTER"

